import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "https://pixcloak.com";
  const now = new Date();
  return [
    { url: `${base}/`, lastModified: now },
    { url: `${base}/compress-es`, lastModified: now },
    { url: `${base}/compress-pt`, lastModified: now },
    { url: `${base}/compress-id`, lastModified: now },
    { url: `${base}/redact`, lastModified: now },
    { url: `${base}/redact-es`, lastModified: now },
    { url: `${base}/redact-pt`, lastModified: now },
    { url: `${base}/redact-id`, lastModified: now },
    { url: `${base}/templates`, lastModified: now },
    { url: `${base}/tools`, lastModified: now },
    { url: `${base}/tools/exif-checker`, lastModified: now },
    { url: `${base}/tools/platform-checker`, lastModified: now },
    { url: `${base}/tools/og-card`, lastModified: now },
    { url: `${base}/tools/favicon-pack`, lastModified: now },
    { url: `${base}/tools/crop-templates`, lastModified: now },
    { url: `${base}/tools/srcset-generator`, lastModified: now },
    { url: `${base}/tools/dataurl-alt`, lastModified: now },
    { url: `${base}/tools/dpi-converter`, lastModified: now },
    { url: `${base}/tools/watermark`, lastModified: now },
    { url: `${base}/tools/lqip`, lastModified: now },
    { url: `${base}/tools/batch-rename`, lastModified: now },
    { url: `${base}/tools/svg-optimizer`, lastModified: now },
    { url: `${base}/tools/text-placeholder`, lastModified: now },
    { url: `${base}/tools/trim-transparent`, lastModified: now },
    { url: `${base}/tools/aspect-pad`, lastModified: now },
    { url: `${base}/press`, lastModified: now },
    { url: `${base}/guides`, lastModified: now },
    { url: `${base}/guides/compress-to-target-kb`, lastModified: now },
    { url: `${base}/guides/es-comprimir-a-kb-objetivo`, lastModified: now },
    { url: `${base}/guides/pt-comprimir-para-kb-alvo`, lastModified: now },
    { url: `${base}/guides/id-kompres-ke-kb-target`, lastModified: now },
    { url: `${base}/guides/redaction-checklist`, lastModified: now },
    { url: `${base}/guides/exif-gps-removal`, lastModified: now },
    { url: `${base}/guides/convert-jpeg-to-webp`, lastModified: now },
    { url: `${base}/guides/resize-longest-side`, lastModified: now },
    {
      url: `${base}/guides/es-redimensionar-lado-mas-largo`,
      lastModified: now,
    },
    {
      url: `${base}/guides/pt-redimensionar-lado-mais-longo`,
      lastModified: now,
    },
    { url: `${base}/guides/id-ubah-ukuran-sisi-terpanjang`, lastModified: now },
    { url: `${base}/guides/compress-to-target-kb-zh`, lastModified: now },
    { url: `${base}/guides/resize-longest-side-zh`, lastModified: now },
    { url: `${base}/guides/rename-rules`, lastModified: now },
    { url: `${base}/guides/license-plate-redaction`, lastModified: now },
    { url: `${base}/guides/screenshot-privacy-check`, lastModified: now },
    { url: `${base}/guides/zip-batch-download`, lastModified: now },
    { url: `${base}/guides/jpeg-vs-webp-size-quality`, lastModified: now },
    { url: `${base}/guides/mobile-upload-limits`, lastModified: now },
    { url: `${base}/guides/social-platform-kb`, lastModified: now },
    { url: `${base}/guides/anonymized-sharing`, lastModified: now },
    { url: `${base}/guides/compress-to-200kb`, lastModified: now },
    { url: `${base}/guides/compress-to-500kb`, lastModified: now },
    { url: `${base}/guides/compress-to-1mb`, lastModified: now },
    { url: `${base}/guides/remove-exif-iphone`, lastModified: now },
    { url: `${base}/guides/remove-exif-wechat`, lastModified: now },
    { url: `${base}/guides/avatar-200kb`, lastModified: now },
    { url: `${base}/guides/post-500kb`, lastModified: now },
    { url: `${base}/guides/jpeg-vs-webp-for-twitter`, lastModified: now },
    { url: `${base}/guides/jpeg-vs-webp-for-linkedin`, lastModified: now },
    { url: `${base}/guides/export-without-metadata`, lastModified: now },
    { url: `${base}/guides/es-exportar-sin-metadatos`, lastModified: now },
    { url: `${base}/guides/pt-exportar-sem-metadados`, lastModified: now },
    { url: `${base}/guides/id-ekspor-tanpa-metadata`, lastModified: now },
    { url: `${base}/guides/platform-image-limits`, lastModified: now },
    {
      url: `${base}/guides/es-limites-de-imagenes-plataformas`,
      lastModified: now,
    },
    {
      url: `${base}/guides/pt-limites-de-imagens-plataformas`,
      lastModified: now,
    },
    { url: `${base}/guides/id-batas-gambar-platform`, lastModified: now },
    { url: `${base}/guides/embed-button`, lastModified: now },
    { url: `${base}/guides/compress-to-300kb`, lastModified: now },
    { url: `${base}/guides/compress-to-800kb`, lastModified: now },
    { url: `${base}/guides/resize-to-1920`, lastModified: now },
    { url: `${base}/guides/prepare-images-for-portfolio`, lastModified: now },
    {
      url: `${base}/guides/prepare-images-for-job-application`,
      lastModified: now,
    },
    { url: `${base}/guides/prepare-images-for-forms`, lastModified: now },
    { url: `${base}/guides/avoid-artifacts-webp-jpeg`, lastModified: now },
    { url: `${base}/guides/research-jpeg-vs-webp`, lastModified: now },
    { url: `${base}/guides/research-500kb-quality-range`, lastModified: now },
    { url: `${base}/guides/es-comprimir-a-200kb`, lastModified: now },
    { url: `${base}/guides/pt-comprimir-para-500kb`, lastModified: now },
    { url: `${base}/guides/id-kompres-menjadi-1mb`, lastModified: now },
    { url: `${base}/guides/platform-image-limits-zh`, lastModified: now },
    { url: `${base}/guides/remove-exif-iphone-zh`, lastModified: now },
    { url: `${base}/guides/remove-exif-wechat-zh`, lastModified: now },
    { url: `${base}/guides/export-without-metadata-zh`, lastModified: now },
    { url: `${base}/privacy`, lastModified: now },
    { url: `${base}/terms`, lastModified: now },
  ];
}
