import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "https://pixcloak.com";
  const coreUpdated = new Date("2025-10-03");
  const toolsUpdated = new Date("2025-10-01");
  return [
    {
      url: `${base}/`,
      lastModified: coreUpdated,
      changeFrequency: "daily" as const,
      priority: 1.0,
    },
    {
      url: `${base}/compress`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 1.0,
    },
    {
      url: `${base}/compress-es`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/compress-pt`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/compress-id`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-es`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-pt`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-id`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/templates`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/tools/exif-checker`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/platform-checker`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/og-card`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/favicon-pack`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/crop-templates`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/srcset-generator`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/dataurl-alt`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/dpi-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/watermark`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/lqip`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/batch-rename`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/svg-optimizer`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/text-placeholder`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/trim-transparent`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/aspect-pad`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/remove-bg-lite`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/webp-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/image-diff`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/sprite-sheet`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/press`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/guides`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/about`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/privacy`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/terms`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/guides/compress-to-target-kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-comprimir-a-kb-objetivo`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-comprimir-para-kb-alvo`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-kompres-ke-kb-target`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/redaction-checklist`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/exif-gps-removal`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/convert-jpeg-to-webp`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/resize-longest-side`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-redimensionar-lado-mas-largo`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-redimensionar-lado-mais-longo`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-ubah-ukuran-sisi-terpanjang`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/compress-to-target-kb-zh`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/resize-longest-side-zh`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/rename-rules`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/license-plate-redaction`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/screenshot-privacy-check`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/zip-batch-download`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/jpeg-vs-webp-size-quality`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/mobile-upload-limits`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/social-platform-kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/anonymized-sharing`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-200kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-500kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-1mb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/remove-exif-iphone`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/remove-exif-wechat`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/avatar-200kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/post-500kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/jpeg-vs-webp-for-twitter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/jpeg-vs-webp-for-linkedin`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/export-without-metadata`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-exportar-sin-metadatos`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-exportar-sem-metadados`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-ekspor-tanpa-metadata`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/platform-image-limits`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-limites-de-imagenes-plataformas`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-limites-de-imagens-plataformas`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-batas-gambar-platform`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/embed-button`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/guides/compress-to-300kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-800kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/resize-to-1920`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/prepare-images-for-portfolio`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/prepare-images-for-job-application`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/prepare-images-for-forms`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/avoid-artifacts-webp-jpeg`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/research-jpeg-vs-webp`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/research-500kb-quality-range`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/guides/es-comprimir-a-200kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-comprimir-para-500kb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-kompres-menjadi-1mb`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/platform-image-limits-zh`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/remove-exif-iphone-zh`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/remove-exif-wechat-zh`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/export-without-metadata-zh`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
  ];
}
