import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "https://pixcloak.com";
  const coreUpdated = new Date("2026-04-24");
  const toolsUpdated = new Date("2026-04-24");
  const guidesRecrawlBoost = new Date("2026-04-24");
  return [
    {
      url: `${base}/`,
      lastModified: coreUpdated,
      changeFrequency: "daily" as const,
      priority: 1.0,
    },
    {
      url: `${base}/compress`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 1.0,
    },
    {
      url: `${base}/compress-es`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/compress-pt`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/compress-id`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-es`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-pt`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-id`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/templates`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/tools/resize-image`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/tools/png-jpg-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/tools/exif-checker`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/platform-checker`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/og-card`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/favicon-pack`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/crop-templates`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/srcset-generator`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/dataurl-alt`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/dpi-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/watermark`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/lqip`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/batch-rename`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/svg-optimizer`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/text-placeholder`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/trim-transparent`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/aspect-pad`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/remove-bg-lite`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/webp-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/image-diff`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/sprite-sheet`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/press`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/research`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/research/docs/compression-algorithm`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/research/docs/privacy-architecture`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/research/docs/benchmarking-methodology`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/guides`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/about`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/privacy`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/terms`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/guides/compress-to-target-kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-comprimir-a-kb-objetivo`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-comprimir-para-kb-alvo`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-kompres-ke-kb-target`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/redaction-checklist`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/exif-gps-removal`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/convert-jpeg-to-webp`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/resize-longest-side`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-redimensionar-lado-mas-largo`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-redimensionar-lado-mais-longo`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-ubah-ukuran-sisi-terpanjang`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/compress-to-target-kb-zh`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/resize-longest-side-zh`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/rename-rules`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/license-plate-redaction`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/screenshot-privacy-check`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/zip-batch-download`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/jpeg-vs-webp-size-quality`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/mobile-upload-limits`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/social-platform-kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/anonymized-sharing`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-200kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-500kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-1mb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/remove-exif-iphone`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/remove-exif-wechat`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/avatar-200kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/post-500kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/jpeg-vs-webp-for-twitter`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/jpeg-vs-webp-for-linkedin`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/export-without-metadata`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-exportar-sin-metadatos`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-exportar-sem-metadados`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-ekspor-tanpa-metadata`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/platform-image-limits`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/es-limites-de-imagenes-plataformas`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-limites-de-imagens-plataformas`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-batas-gambar-platform`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/embed-button`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/guides/compress-to-300kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/compress-to-800kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/resize-to-1920`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/prepare-images-for-portfolio`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/prepare-images-for-job-application`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/prepare-images-for-forms`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/guides/avoid-artifacts-webp-jpeg`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/research-jpeg-vs-webp`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/research-500kb-quality-range`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/guides/es-comprimir-a-200kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/pt-comprimir-para-500kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/id-kompres-menjadi-1mb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/platform-image-limits-zh`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/remove-exif-iphone-zh`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/remove-exif-wechat-zh`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/export-without-metadata-zh`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/how-to-compress-image-without-losing-quality`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/guides/gsc-operations`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      url: `${base}/guides/convert-jpg-to-webp-online`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      url: `${base}/guides/blur-number-plate-online`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      url: `${base}/guides/complete-image-compression-guide`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.78,
    },
    {
      url: `${base}/guides/research-quality-size-curves`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.68,
    },
    {
      url: `${base}/guides/how-to-resize-images-for-instagram`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/guides/languages`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      url: `${base}/guides/redact-screenshot-mac`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/black-out-text-in-image`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/guides/image-seo-optimization`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
    {
      url: `${base}/guides/remove-gps-data-from-photos`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/guides/privacy-compliance`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/guides/long-tail`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      url: `${base}/guides/long-tail/compress-to-100kb-for-email`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/guides/long-tail/compress-to-500kb-for-instagram`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/guides/long-tail/compress-to-200kb-for-linkedin`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/guides/tinypng-alternative-free-no-upload`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.76,
    },
    {
      url: `${base}/guides/compress-image-to-100kb`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.76,
    },
    {
      url: `${base}/guides/how-to-reduce-image-file-size`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.76,
    },
    {
      url: `${base}/guides/how-to-compress-on-iphone`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      url: `${base}/guides/png-vs-jpg-when-to-use-each`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.74,
    },
    {
      url: `${base}/guides/blur-face-in-photo`,
      lastModified: guidesRecrawlBoost,
      changeFrequency: "monthly" as const,
      priority: 0.72,
    },
  ];
}
