import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "https://pixcloak.com";
  const coreUpdated = new Date("2026-04-24");
  const toolsUpdated = new Date("2026-04-24");
  // All /guides/* URLs live in app/guides/sitemap.ts only (single source of truth).
  return [
    {
      url: `${base}/`,
      lastModified: coreUpdated,
      changeFrequency: "daily" as const,
      priority: 1.0,
    },
    {
      url: `${base}/compress`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 1.0,
    },
    {
      url: `${base}/compress-es`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/compress-pt`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/compress-id`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-es`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-pt`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/redact-id`,
      lastModified: coreUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    {
      url: `${base}/templates`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/scenarios`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/embed`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/embed/compress`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/tools`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    },
    {
      url: `${base}/tools/resize-image`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/tools/png-jpg-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/tools/rotate-flip`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/tools/heic-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.75,
    },
    {
      url: `${base}/tools/pdf-to-image`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.72,
    },
    {
      url: `${base}/tools/exif-checker`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/platform-checker`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/og-card`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/favicon-pack`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/crop-templates`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/srcset-generator`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/dataurl-alt`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/dpi-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/watermark`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/lqip`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/batch-rename`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/svg-optimizer`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/text-placeholder`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/trim-transparent`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/aspect-pad`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/remove-bg-lite`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/webp-converter`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/image-diff`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/tools/sprite-sheet`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    {
      url: `${base}/press`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/facts`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/gallery`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.6,
    },
    {
      url: `${base}/case-studies`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/testimonials`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/benchmark`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/changelog`,
      lastModified: toolsUpdated,
      changeFrequency: "weekly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/research`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.65,
    },
    {
      url: `${base}/research/docs/compression-algorithm`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/research/docs/privacy-architecture`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/research/docs/benchmarking-methodology`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.55,
    },
    {
      url: `${base}/about`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/privacy`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/terms`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.5,
    },
    {
      url: `${base}/contact`,
      lastModified: toolsUpdated,
      changeFrequency: "monthly" as const,
      priority: 0.45,
    },
  ];
}
