import { TemplatePreset } from "@/types/templates";

export const TEMPLATES: TemplatePreset[] = [
  {
    slug: "wechat-chat-redact",
    title: "微信聊天截图脱敏",
    scene: "redact",
    summary: "一键打码昵称、头像区、手机号与二维码，分享前合规发布。",
    highlights: ["预设遮蔽常见区域", "强像素化/实色块", "EXIF/GPS清除"],
    ctaHref: "/redact",
  },
  {
    slug: "license-plate-redact",
    title: "车牌信息打码",
    scene: "redact",
    summary: "曝光路况/事故前，快速遮蔽车牌并留安全边距。",
    highlights: ["不可逆遮蔽", "多张批量处理（即将）", "合规提醒"],
    ctaHref: "/redact",
  },
  {
    slug: "id-card-redact",
    title: "证件/工牌关键信息遮蔽",
    scene: "redact",
    summary: "分享证件照或工牌前，遮蔽号码与敏感字段。",
    highlights: ["模板化规则", "像素化/实色切换", "导出报告（企业版）"],
    ctaHref: "/redact",
  },
  {
    slug: "contract-info-redact",
    title: "合同/票据隐私处理",
    scene: "redact",
    summary: "对外发送前打码姓名、电话、地址、账号等敏感信息。",
    highlights: ["OCR建议框（后续）", "手动校对", "批量导出（即将）"],
    ctaHref: "/redact",
  },
  {
    slug: "social-post-redact",
    title: "社媒发布前隐私检查",
    scene: "redact",
    summary: "发微博/小红书/朋友圈前一键检查敏感信息并遮蔽。",
    highlights: ["平台规格提示", "模板一键套用", "本地处理不上传"],
    ctaHref: "/redact",
  },
  {
    slug: "exif-gps-clean",
    title: "EXIF/GPS 一键清除",
    scene: "redact",
    summary: "移除位置信息与拍摄设备信息，保护隐私。",
    highlights: ["本地重编码", "不上传", "批量处理（即将）"],
    ctaHref: "/redact",
  },
  {
    slug: "target-size-200kb",
    title: "压缩至 200KB（网站/表单）",
    scene: "compress",
    summary: "针对常见上传限制，自动尝试合适质量达到目标体积。",
    highlights: ["目标体积优先", "多图批量", "ZIP 打包下载"],
    ctaHref: "/compress",
  },
  {
    slug: "target-size-500kb",
    title: "压缩至 500KB（社媒/电商）",
    scene: "compress",
    summary: "保持清晰度同时满足平台大小限制。",
    highlights: ["质量滑杆", "结果预览", "批量打包"],
    ctaHref: "/compress",
  },
  {
    slug: "jpg-to-webp",
    title: "JPG → WebP（体积更小）",
    scene: "compress",
    summary: "转换更高压缩比的格式，适合网站与H5。",
    highlights: ["本地格式转换（后续）", "预览对比", "批量"],
    ctaHref: "/compress",
  },
  {
    slug: "heic-to-jpg",
    title: "HEIC → JPG（iPhone 照片）",
    scene: "compress",
    summary: "兼容更多平台，便于上传分享。",
    highlights: ["本地转换（后续）", "批量处理", "ZIP 导出"],
    ctaHref: "/compress",
  },
];
